### ISSUE TITLE
No atom prefix declared in harm.ttl

### ISSUE THREAD

**Issue by mxmilkiib** [Stazed/rakarrack#42]
Via Yruama in #lv2

**Comment by trebmuh** [comment]
ping @yruamalairba

**Comment by Stazed** [comment]
I assume you are talking about harm.ttl, not harm_no_midi.ttl. This .ttl was imported from rkrlv2 and was never completed. It is not included in the manifest.ttl. It was most likely to be the midi version. I will remove it to avoid any further confusion.

FYI, this repository will no longer be developed. The project has been forked but is not ready for public consumption. Should be ready in a few weeks. The new project "rakarrack-plus" will have a  midi version for both the Harmonizer and the Stereo Harmonizer.
